### ISSUE TITLE
[Data18] Actor images are blank files

### ISSUE THREAD

**Issue by d2dyno** [DoctorD1501/JAVMovieScraper#207]
I have noticed an issue lately, where actor images are being written as blank files.

URL reported by JMS: https://i.datavimg.com/images/stars/120/24164.jpg
Proper url from data18.com: https://i.datavimg.com/images/stars/pic4/24164.jpg

Although, in the web browser, it seems both report 403 errors for me?

**Comment by Chkm7te** [comment]
Getting the same, no images for actors although they are shown through the browser.

**Comment by rod8687** [comment]
it's not loading the Posters or Fanart for me in addition tho the actors,
I guess Data18 changes somthing on their website

**Comment by Cutters1982** [comment]
seems they've blocked hotlinking their images annoyingly :(

**Comment by Wizell** [comment]
This should be fixed by v0.3.2.

**Comment by rod8687** [comment]
Hey, thanks for looking into this, I've just tried it and it's still not pulling the posters or the Fanart

**Comment by d2dyno** [comment]
I can confirm, actor images are still broken in 0.3.2

**Comment by Wizell** [comment]
@rod8687 This issue is not about fanart or posters so please post in corresponding issues

@d2dyno From the tests i made the actors are scrapped properly. Can you give an example where it doesn't work ?

**Comment by d2dyno** [comment]
@Wizell here is the log with error:
`fileBaseName = daughters.16.04.15.april.brookes.and.serenity.haze.grounded.girls
Scraping this webpage for movie: http://www.data18.com/content/1163856
Title by Property: Grounded Girls
Original Title by Property: Grounded Girls, w/ April Brookes, Serenity Haze in Daughter Swap - data18.com
Official Poster: Thumb [thumbURL=https://i.datavimg.com/media/scenes/1/7/163856-april-brookes-serenity-haze-eric-john-daughter-swap.jpg" source="Default Data Item Source"]
Starring: Eric John
Starring: Filthy Rich
Scraping complete of siteScraper = Data18 Web Content
Skipping amalgamation process as there is only one movie
returning option picked from panel = Thumb [thumbURL=https://i1.datavimg.com/348/3045/163856/13.jpg" source="Data18 Web Content"]
returning option picked from panel = Thumb [thumbURL=https://i1.datavimg.com/348/3045/163856/11.jpg" source="Data18 Web Content"]
Movie Size: 1
java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/120/16938.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:41)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:29)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:283)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getImageIconForLabelName(ActressListRenderer.java:136)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getListCellRendererComponent(ActressListRenderer.java:60)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by Wizell** [comment]
@d2dyno Thank you for the informations. I made a fix in v0.3.3, can you try it ?

**Comment by d2dyno** [comment]
@Wizell seems to have same issue:
```currentItemSource = Data18 Web Content with disabled = false
U:\BTSync\Misc\2160p\mydaughtershotfriend.17.06.18.elsa.jean.4k.mp4
currentItemSource = Default Data Item Source with disabled = false
Prompting the user for a url for Data18 Web Content
fileBaseName = mydaughtershotfriend.17.06.18.elsa.jean.4k
Scraping this webpage for movie: http://www.data18.com/content/1177470
Title by Property: Elsa Jean in My Daughter's Hot Friend
Original Title by Property: Elsa Jean in My Daughter's Hot Friend ( June 2017 ) Naughty America - data18.com
Official Poster: Thumb [thumbURL=https://i.datavimg.com/media/scenes/1/8/177470-elsa-jean-mick-blue-my-daughters-hot-friend.jpg" source="Default Data Item Source"]
Starring: Elsa Jean
Starring: Mick Blue
Scraping complete of siteScraper = Data18 Web Content
Skipping amalgamation process as there is only one movie
returning option picked from panel = Thumb [thumbURL=https://i1.datavimg.com/47/3044/177470/02.jpg" source="Data18 Web Content"]
returning option picked from panel = Thumb [thumbURL=https://i1.datavimg.com/47/3044/177470/03.jpg" source="Data18 Web Content"]
Movie Size: 1
java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/120/25700.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:41)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:29)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:283)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getImageIconForLabelName(ActressListRenderer.java:127)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getListCellRendererComponent(ActressListRenderer.java:60)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/120/6316.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:41)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:29)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:283)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getImageIconForLabelName(ActressListRenderer.java:127)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getListCellRendererComponent(ActressListRenderer.java:60)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by d2dyno** [comment]
I spoke too soon. Actor images seem to be writing correctly. They just are not showing pre-writing like they used to, and I am thinking that is where the above error is from.

**Comment by CuddleBear92** [comment]
If people still have issues with this and want a quick and dirty bulk fix for all the nfo files. 
Just load up notepad++ and press Ctrl+H and ask it to find `/images/stars/120/` and replace with `/images/stars/pic4/`
Set *.nfo as a filter and point it to your root folder and press replace in files. 
This will check all .nfo files and replace those parts of the url with the other.
![notepad _2018-08-02_16-57-06](https://user-images.githubusercontent.com/8496821/43592103-1fdfb154-9675-11e8-96ca-a6dae24dcc92.png)


Official support for a regex replacement on the scraper itself is a must no matter what though! 
As this is still happening on v0.3.4

**Comment by d2dyno** [comment]
I haven't had this issue in quite some time. I'm going to close this, unless someone else can provide logs/information of this happening to them.
